on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Exécution d'une commande simple
        run: echo "Pipeline Lab 12 exécuté avec succès !"
